[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
[".emacs.d"]
    type = "git-repo"
    url = "https://github.com/doomemacs/doomemacs.git"
    refreshPeriod = "168h"
    args = ["--depth 1"]
