#!/bin/bash

## Notify user about which display profile that is in use
notify-send -i display "Display profile" "$AUTORANDR_CURRENT_PROFILE"

## Restart polybar
~/.config/polybar/launch.sh

# Set background
feh --no-fehbg --bg-scale '~/.local/share/backgrounds/nord-arch-fullnamelogo.png' &
